### PR TITLE
Added CI Test for Master Calibrations Recipe

### PR DESCRIPTION
**Pull request by bjfultn**
- tests now take just over 1 hour to run

### CODE REVIEW

**Comment by bjfultn** [comment]
@RussLaher please check that the file path adjustments I made in the config files are ok.

**Comment by RussLaher** [comment]
I approve.  Again, I will check in my changes to modules/master_flat/src/master_flat_framework.py and kpf_masters_drp.cfg tomorrow morning.

**Review by RussLaher — APPROVED** [review]
Looks good.  I updated the files in my /data/user/rlaher/sbx/reference_fits, so the masters pipeline will not be broken.

**Comment by bjfultn** [comment]
Also includes issue #645

**Pull request merged**
