### PR TITLE
Feature/bug fix 20230616

### PR DESCRIPTION
**Pull request by RussLaher**
Please merge the feature/bug_fix_20230616 branch into the develop branch.

### CODE REVIEW

**Comment by awhoward** [comment]
Minor point: I think this is supposed to be merged into develop, not master.

**Comment by RussLaher** [comment]
I think "merging into master" is some sort of standard github template message.  I specifically requested merging into the develop branch (as I always do).

**Comment by awhoward** [comment]
Hi Russ. FWIW, I was responding to the top of the page (see attached screenshot).
IMG_1946

**Comment by RussLaher** [comment]
Hi Andrew,

Yes, I saw that message, which I thought was a github template, since I cannot seem to change it under the web browser PR.  But it is possible that I am using the wrong git push command.  Here is what I used:

git push --set-upstream origin feature/bug_fix_20230616

BJ, please let me know if this is incorrect.  Thanks.

Regards,

Russ

Russ Laher, PhD, MBA | Applications Developer | Caltech/IPAC
Mail Code MR-100 | Pasadena CA 91125 | ***@***.***

**Comment by bjfultn** [comment]
When you create a PR on the web interface there is a drop down menu to select the "base" branch. This is the branch you want to be sure is develop.
image

**Review by bjfultn — APPROVED** [review]

**Pull request merged**
