### PR TITLE
Create dictionary of WLS parameters

### PR DESCRIPTION
**Pull request by awhoward**
This pull request contains numerous updates to the WLS code to make WLS dictionaries.  I put a placeholder [here](https://kpf-pipeline.readthedocs.io/en/docs-pipeline-info/info/data_format.html) for documentation to explain the format of WLS dictionaries.  In brief, WLS dictionaries are hierarchical dictionaries that store information about fits to individual lines, fits of those lines across individual orders, and additional information organized by orderlet.

I _think_ the wls_auto.recipe works, but I hope that others can try it out since there are major changes. @aaronhouseholder @bjfultn 

The wls_auto.recipe will put compressed JSON files in the same directory as the output L1 WLS file.

This update also includes a new set of analysis methods in the AnalyzeWLS class (`modules/Utils/analyze_wls.py`).  I will post an explainer about this soon.

A new utility function called get_kpf_echelle_order() will return the echelle order of a wavelength.

### CODE REVIEW

**Comment by awhoward** [comment]
@bjfultn -- I'm having trouble determining if the failure above is meaningful or not.  I see the error reproduced below, but I'm not sure if that's the only issue.

----------------

Sending e-mails to: bfulton@ipac.caltech.edu bjfultn@gmail.com
ERROR: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials s12-20020a170902988c00b001c0cb2aa2easm1463726plp.121 - gsmtp

javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials s12-20020a170902988c00b001c0cb2aa2easm1463726plp.121 - gsmtp

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:947)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:858)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:762)
	at javax.mail.Service.connect(Service.java:364)
	at javax.mail.Service.connect(Service.java:222)
	at javax.mail.Service.connect(Service.java:171)
	at javax.mail.Transport.send0(Transport.java:230)
	at javax.mail.Transport.send(Transport.java:100)
	at hudson.tasks.MailSender.run(MailSender.java:130)
	at hudson.tasks.Mailer.perform(Mailer.java:176)
	at hudson.tasks.Mailer.perform(Mailer.java:139)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:752)
	at hudson.model.Build$BuildExecution.post2(Build.java:177)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:697)
	at hudson.model.Run.execute(Run.java:1932)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE

**Comment by awhoward** [comment]
It looks like the error happens for another pull request.  https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/pull/718

**Comment by bjfultn** [comment]
@awhoward @aaronhouseholder could you guys work out this conflict together? I'm not sure which code to adopt.

**Comment by awhoward** [comment]
@aaronhouseholder -- we might chat tomorrow at the WLS meeting.

**Comment by aaronhouseholder** [comment]
@awhoward sounds good! A walk-through of these updates will be helpful for me to try to figure out what's happening here.

**Pull request merged**
