### PR TITLE
Feature/quicklook

### PR DESCRIPTION
**Pull request by awhoward**
This is a substantial update to the Quicklook pipeline to refactor it for modularity and to add several features.  With this pull request, I'm asking those familiar with this part of the code (@bjfultn and @fdai-planet), as well as other interested folks, to review the changes.  I'm still running some tests and may make a few other updates.  But if there are architectural or other significant problems, it would be helpful to know now so that I can address them.  I expect to submit another pull request (without the "don't merge" tag) in another day or two.

The analysis and plotting functions of the QLP have been moved to a set of "Analysis" classes in {`analyze_2d.py  analyze_em.py  analyze_guider.py  analyze_hk.py  analyze_l0.py  analyze_l1.py  analyze_l2.py`} in `modules/Utils/`.  If desired, this functionality can be invoked outside of the QLP in Jupyter Notebooks, other recipes, etc.

I created two new recipes for generating QLP content.  The "datecode" recipe computes QLP products for all KPF data products with a particular date code (e.g., 20230720).  The "one file" recipe does the same for a single ObsID (or multiple ObsID using wildcards).  There are booleans in the config files that determine which sets of QLP products are generated (L0, 2D, L1, L2).  The code below shows how to invoke the two recipes.  These can be easily adapted for other uses including in the main recipe.
```
kpf -c configs/quicklook_datecode.cfg -r recipes/quicklook_datecode.recipe
kpf -c configs/quicklook_one_file.cfg -r recipes/quicklook_one_file.recipe
```

The old Quicklook recipe is completely broken with this update, so it will take a little work to update the DRP infrastructure to work with this.  I think it will only involve lines like `Quicklook(KPF_object, output_path, QLP_level)` in recipes triggered by file creation, where `KPF_object` is a L0/2D/L1/L2 object, `output_path` is like `/data/QLP/20230720/` and `QLP_level` is one of "L0", "2D", "L1", "L2".

Some new features are:

- Guider QLP data products
- 3x3 zoom-in images of the 2D files to show details
- More extensive orderlet ratio plots that highlight some processing issues
- More extensive CCF plots (for all orderlets)

I tried to put consistent logging statements in place using self.logger so that one can follow progress more easily.  There are also low-level try/except statements throughout so that little hangups only cause contained problems.

I've done some testing, but more is needed.  To date, I've run it extensively on a handful of carefully selected observations.  I'm currently running it on all files in 20230720 and the results will be ready in a few hours.  However, the DRP has worked through the nighttime observations so you can see the results.  [Here's an example](https://jump.caltech.edu/observing-logs/kpf/KP.20230720.39925.96) on Jump.  I'm not aware of any major problems with the new QLP, but I bet that some corner cases will reveal themselves with additional testing.  The runtime for all of L0/2D/L1/L2 is about 3 minutes per ObsID.  So, absent multiprocessing, it's hard for me to test more thoroughly.  If no major issues are identified, I suggest deploying this in production and I'll do my best to respond to issues as they arise.

The runtime of ~3 min per exposure is manageable, but not as fast as I'd like.  At least half of the time is spent in plt.savefig() and the big L0 and 2D images take 12-15 seconds each.  I spent some time trying to optimize this.  I've already optimized the resolution (dpi setting) for each graphic so that we can just resolve the images and spectra.  I don't think there's an additional speed-up here unless we make the images/plots undersampled.  The internet has some other wisdom that didn't fully pan out when I tried it (e.g., using a different backend in matplotlib).  L1 is actually the slowest overall because it produces the most plots.  L2 is the fastest.  Suggestions for speed-ups are welcome.  One that I can work on is not computing some data products when they're not needed (e.g., CCF plots for flats).  This is perhaps only a 10-20% savings in computing time though.

The documentation is in a partial state of completeness.  The "Analysis" classes are reasonably well documented, though I want to polish this.  The Quicklook class (`cd modules/quicklook/src/alg.py`) has nicely formatted code with comments throughout, but I should really add some summary documentation at the top.

Some to-do items:

- Port a few remaining features from the old version of the QLP.  These are in qlp_procedures() in `modules/quicklook/src/alg.py` (some are commented out) and include the treatment of masters, annotated 2D images for bias/darks, and read noise analysis of bias frames.
- Move the extraction of Ca HK spectra to the main pipeline (!) and do it with a proper extraction tool.
- More comprehensive documentation (see above) and perhaps a Tutorial on using QLP functions in a notebook.
- Polishing the Guider QLP products.  Josh Walawender has some nice examples of this.
- Update the Exposure Meter time series by separating the SCI and SKY traces onto separate plots to reveal additional detail.
- Fix some commented-out code in `analyze_l2.py/plot_CCF_grid()`.
- Develop a recipe to reprocess all QLP (or for some date range).  Multiprocessing will be needed.  I'm not sure how to do this.  Is there an example of this, @bjfultn?

Comments are welcome on all of this.  A huge thanks to @fdai-planet for all of his work on the QLP.  There was a great foundation to build off of!  I hope that we can continue to collaborate on the QLP.  Digging into the code has been a learning experience for me that I can apply to other parts of the DRP.

### CODE REVIEW

**Comment by howardisaacson** [comment]
Here are my comments on the new-look plots. I do not see any issues that would prevent this new functionality, but there some future options, and additions. 

Guider tab:
    - 3 panel plot:  left and center pots: This is helpful for knowing the average seeing measurement and consistency. It is not informative if the star is in the correct position. Is there a way to show that? One the residuals panel (far right), can the color scale be 10% of the range of the guider, or perhaps some dynamic range. Currently the residuals are not visible
    - On the guider error time series plot, and 2D projection: Can the 2D projection be centered at [0,0]? This would help for consistency and building intuition about what the plot should look like. If the axis range is dynamic, I recommend it be static, for easy comparison.
    - For the guiding flux time series plot, would the y-axis be better if it were in magnitudes rather than fractional flux? Maybe knowing if there is one magnitude of variability is more useful than the associated fraction.
- L2 Tab:
    - 5 panel CCF plots are awesome!  I really like seeing all of the CCFs, even if they are not all used.
- EM tab
    - For the exposure meter time series, having magnitudes on the y-axis is more intuitive than the current plot.
    - Even though I think I understand the dashed lines, only the sky dashed line is labeled in the legend.
- L0 tab:
    - Good as is, one improvement would be an enlargement of one small section of the L2 file so that the indivdual traces are more easily visible. I was thinking picture-in-picture style with a ~50x50 pixel inset.
- L2 tab
    - I like the aditional grids of blow-ups of certain parts of the 2D image.
    - I do not find the histogram of the 2D images useful. Perhaps more experience will allow me to use these effectively.
- L1 tab
    - The most useful plot in the one that shows the full 1D spectrum for both CCDs, using 9 rows. There is one for SCI1,SCI2,SCI3. I think these should be presented as the first plots, so no scrolling is needed to see them.
    - The 9-row plot of the sky image can have an improved y-axis so that the plot is not smashed vertically.
    - The L1(CAL) plots that a single order could be annotated with a ‘target SNR’ so that we can assess the lamps, and filters used and if they should be adjusted.

**Comment by awhoward** [comment]
Thanks for all of the great comments, @howardisaacson !  I’ll work on implementing these.

**Comment by awhoward** [comment]
A few comments (with more to follow).  

The ordering of plots within a subtab is important to think about (as you pointed out).  It looks like the display order is controlled by file creation date, not alphabetical (which would be more convenient) although I may have found an exception -- I need to double check.  Let's think about this.  I changed the order for the EM plots by changing the order of executing of the QLP code.  This may not be possible in all cases though.  Maybe we should ask Jake to change the sorting to be alphabetical.

I'm trying a new version of the EM time series plot.  Instead of log, the plot is now linear on the vertical axis.  I've also separated sky and sci so that they're both visible.  Let me know what you think.  If we do want to go with magnitudes, I could change it back to log and then use magnitude labels on the vertical axis instead of log10.  Let me know what you think.  See an example of the new version here: https://jump.caltech.edu/observing-logs/kpf/KP.20230724.53391.74

I also made the ordering adjustment that you suggested for L1.  Actually, I put the one SNR plot first (which I find useful and it's only one plot), then the five 9-panel plots of spectra.

I'll work on getting more information into the Guider plot, as you described.  Adding jmag and gmag would also be helpful.

**Comment by bjfultn** [comment]
Does the datecode recipe use the `--date` command line flag? If not it should. You can access that within the recipe as `context.date_dir`

**Comment by bjfultn** [comment]
Once you can call it like `kpf --date <date_code> -c configs/quicklook_datecode.cfg -r recipes/quicklook_datecode.recipe` then you can make a bash script with one line like that for each date that you want to reprocess and then use `parallel` to process all of the dates at once like this: `cat <script> | parallel -j <ncpus>`

**Comment by bjfultn** [comment]
Context only contains `date_dir` and `file_path` the latter comes from file events in watch mode. I could add more variables to context but they should be broadly applicable for any recipe.

**Comment by awhoward** [comment]
Roger that on `date_dir` and `file_path`, @bjfultn.  No need to create additional context.  Thanks.

**Comment by awhoward** [comment]
Note to self on additional QLP features to add:

- EM flux ratios for SKY/SCI (new plot)
- some information about target SNR in the EM

**Comment by awhoward** [comment]
Closing to submit an updated version of this PR with a few changes.

**Pull request closed without merging**
